/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */


export type paths = {
  "/": {
    /**
     * API Home
     * @description The home endpoint for this API. Displays basic informational message
     */
    get: operations["apiHome"];
  };
  "/search": {
    /**
     * Search Cards
     * @description Search for, and list trading game cards that match a search term
     */
    get: operations["searchCards"];
  };
  "/users": {
    /**
     * Create a user
     * @description Add a new user with their unique nickname and password
     */
    post: operations["createUser"];
  };
  "/users/me": {
    /**
     * Get the current user
     * @description Get the currently authenticated user
     */
    get: operations["getCurrentUser"];
  };
  "/users/{userId}/favorites": {
    /**
     * Remove a card from a user's favorites
     * @description Remove a card from a user's favorites. If the card is not in the user's favorites, this operation will be ignored.
     */
    delete: operations["removeFromFavorites"];
    /**
     * Add a card to a user's favorites
     * @description Add a card to a user's favorites. If the card is already in the user's favorites, this operation will be ignored.
     */
    patch: operations["addToFavorites"];
  };
  "/authenticate": {
    /**
     * Authenticate a user
     * @description Authenticate a user with their nickname and password
     */
    post: operations["authenticate"];
  };
};

export type webhooks = Record<string, never>;

export type components = {
  schemas: {
    /**
     * @default 1
     * @example 1
     */
    PageParam: number;
    /** @example pokey */
    SearchTermParam: string;
    /**
     * @default name
     * @example name
     * @enum {string}
     */
    OrderByParam: "name" | "released";
    /**
     * @default AUTO
     * @example AUTO
     * @enum {string}
     */
    SortDirParam: "ASC" | "DESC" | "AUTO";
    APIWelcome: {
      /** @example Welcome to the API backend for the trading game cards MVP */
      message: string;
    };
    CardImageURIs: {
      /**
       * Format: uri
       * @example https://placehold.co/146x204?text=No+Image
       */
      small?: string;
      /**
       * Format: uri
       * @example https://placehold.co/488x680?text=No+Image
       */
      normal?: string;
      /**
       * Format: uri
       * @example https://placehold.co/666x927?text=No+Image
       */
      large?: string;
    };
    CardPrices: {
      /** @example 0.25 */
      usd?: string;
      /** @example 0.10 */
      eur?: string;
    };
    Card: {
      /** @example d99a9a7d-d9ca-4c11-80ab-e39d5943a315 */
      id: string;
      /** @example en */
      lang: string;
      /** @example Aerial Predation */
      name: string;
      /** @example d99a9a7d-d9ca-4c11-80ab-e39d5943a315 */
      uri: string;
      /** @example rare */
      rarity: string;
      /** @example Modern Horizons */
      set_name: string;
      /** @example 186 */
      collector_number?: number;
      /**
       * Format: date
       * @example "2021-06-18T00:00:00.000Z"
       */
      released_at: string;
      games?: string[];
      image_uris: components["schemas"]["CardImageURIs"];
      nonfoil: boolean;
      foil: boolean;
      prices: components["schemas"]["CardPrices"];
    };
    Pagination: {
      /**
       * @description A link to the next page of responses if one exists
       * @example /search?term=red&page=3
       */
      next?: string;
      /**
       * @description A link to the previous page of responses if one exists
       * @example /search?term=red&page=1
       */
      previous?: string;
    };
    QueryResult: {
      /** @description The total number of cards matching the search query */
      total: number;
      /** @description A page of the cards matching the search query */
      data: components["schemas"]["Card"][];
    };
    CardsQueryResponse: components["schemas"]["QueryResult"] & components["schemas"]["Pagination"];
    /**
     * Format: uuid
     * @example d99a9a7d-d9ca-4c11-80ab-e39d5943a315
     */
    FavCard: string;
    Nickname: string;
    UserId: string;
    UserDto: {
      id: components["schemas"]["UserId"];
      nickname: components["schemas"]["Nickname"];
      /** @description A list of cardsmarked as favorites by this user */
      favorites?: components["schemas"]["FavCard"][];
    };
    UserCreatedDto: {
      id: components["schemas"]["UserId"];
    };
    CreateUserDto: {
      nickname: components["schemas"]["Nickname"];
      password: string;
    };
    LoginAttempt: {
      nickname: components["schemas"]["Nickname"];
      password: string;
      /** @default false */
      createUser?: boolean;
    };
    AuthToken: {
      token: string;
    };
    FavCardDto: {
      card: components["schemas"]["FavCard"];
    };
    APIError: {
      message?: string;
      path?: string;
    };
    APIResponseError: {
      /** @description The error message from the server */
      message: string;
      code?: number;
      errors?: components["schemas"]["APIError"][];
    };
  };
  responses: {
    /** @description Bad request */
    BadRequest: {
      content: {
        "application/json": components["schemas"]["APIResponseError"];
      };
    };
    /** @description Unauthorized */
    Unauthorized: {
      content: {
        "application/json": components["schemas"]["APIResponseError"];
      };
    };
    /** @description Forbidden */
    Forbidden: {
      content: {
        "application/json": components["schemas"]["APIResponseError"];
      };
    };
    /** @description Too many requests */
    TooManyRequests: {
      content: {
        "application/json": components["schemas"]["APIResponseError"];
      };
    };
    /** @description Internal server error */
    InternalServerError: {
      content: {
        "application/json": components["schemas"]["APIResponseError"];
      };
    };
  };
  parameters: {
    /** @description The ID of a user to retrieve */
    userId: components["schemas"]["UserId"];
    /** @description The search term to find cards with */
    searchTerm: components["schemas"]["SearchTermParam"];
    /** @description On what property to order the matching cards. Default is `name` */
    orderBy?: components["schemas"]["OrderByParam"];
    /**
     * @description The sort order of the returned cards. Default is `AUTO` Sort order:
     *   * `ASC` - Ascending, from A to Z
     *   * `DESC` - Descending, from Z to A
     *   * `AUTO` - Allow the system choose the most inuitive direction to sort.
     */
    sortDir?: components["schemas"]["SortDirParam"];
    /** @description The page of the matching resultset to return. Default is `1`. */
    page?: components["schemas"]["PageParam"];
    tempPath: string;
  };
  requestBodies: never;
  headers: never;
  pathItems: never;
};

export type $defs = Record<string, never>;

export type external = Record<string, never>;

export type operations = {

  /**
   * API Home
   * @description The home endpoint for this API. Displays basic informational message
   */
  apiHome: {
    responses: {
      /** @description A basic informational message about the search cards API */
      200: {
        content: {
          "application/json": components["schemas"]["APIWelcome"];
        };
      };
      400: components["responses"]["BadRequest"];
      429: components["responses"]["TooManyRequests"];
      500: components["responses"]["InternalServerError"];
    };
  };
  /**
   * Search Cards
   * @description Search for, and list trading game cards that match a search term
   */
  searchCards: {
    parameters: {
      query: {
        term: components["parameters"]["searchTerm"];
        orderby?: components["parameters"]["orderBy"];
        sortdir?: components["parameters"]["sortDir"];
        page?: components["parameters"]["page"];
      };
    };
    responses: {
      /** @description A paged list of cards matching the search term */
      200: {
        content: {
          "application/json": components["schemas"]["CardsQueryResponse"];
        };
      };
      400: components["responses"]["BadRequest"];
      429: components["responses"]["TooManyRequests"];
      500: components["responses"]["InternalServerError"];
    };
  };
  /**
   * Create a user
   * @description Add a new user with their unique nickname and password
   */
  createUser: {
    requestBody?: {
      content: {
        "application/json": components["schemas"]["CreateUserDto"];
      };
    };
    responses: {
      /** @description The newly created user */
      201: {
        content: {
          "application/json": components["schemas"]["UserCreatedDto"];
        };
      };
      400: components["responses"]["BadRequest"];
      429: components["responses"]["TooManyRequests"];
      500: components["responses"]["InternalServerError"];
    };
  };
  /**
   * Get the current user
   * @description Get the currently authenticated user
   */
  getCurrentUser: {
    responses: {
      /** @description The authenticated user */
      200: {
        content: {
          "application/json": components["schemas"]["UserDto"];
        };
      };
      400: components["responses"]["BadRequest"];
      429: components["responses"]["TooManyRequests"];
      500: components["responses"]["InternalServerError"];
    };
  };
  /**
   * Remove a card from a user's favorites
   * @description Remove a card from a user's favorites. If the card is not in the user's favorites, this operation will be ignored.
   */
  removeFromFavorites: {
    parameters: {
      path: {
        userId: components["parameters"]["userId"];
      };
    };
    requestBody?: {
      content: {
        "application/json": components["schemas"]["FavCardDto"];
      };
    };
    responses: {
      /** @description The card was removed from the user's favorites */
      204: {
        content: never;
      };
      400: components["responses"]["BadRequest"];
      429: components["responses"]["TooManyRequests"];
      500: components["responses"]["InternalServerError"];
    };
  };
  /**
   * Add a card to a user's favorites
   * @description Add a card to a user's favorites. If the card is already in the user's favorites, this operation will be ignored.
   */
  addToFavorites: {
    parameters: {
      path: {
        userId: components["parameters"]["userId"];
      };
    };
    requestBody?: {
      content: {
        "application/json": components["schemas"]["FavCardDto"];
      };
    };
    responses: {
      /** @description The card was added to the user's favorites */
      204: {
        content: never;
      };
      400: components["responses"]["BadRequest"];
      429: components["responses"]["TooManyRequests"];
      500: components["responses"]["InternalServerError"];
    };
  };
  /**
   * Authenticate a user
   * @description Authenticate a user with their nickname and password
   */
  authenticate: {
    requestBody?: {
      content: {
        "application/json": components["schemas"]["LoginAttempt"];
      };
    };
    responses: {
      /** @description A JWT for the authenticated user */
      200: {
        content: {
          "application/json": components["schemas"]["AuthToken"];
        };
      };
      400: components["responses"]["BadRequest"];
      429: components["responses"]["TooManyRequests"];
      500: components["responses"]["InternalServerError"];
    };
  };
};
